### PR TITLE
 Replace Vapor to AsyncHTTPClient

### PR DESCRIPTION
**Pull request by vkill**
Hi, there

The AsyncHTTPClient is very easy to use, please review it. thx.

### CODE REVIEW

**Comment by vkill** [comment]
@anthonycastelli

**Comment by anthonycastelli** [comment]
@vkill Is it really necessary to use a 3rd party HTTP library instead of Vapor/NIO?

**Comment by vkill** [comment]
Vapor also use AsyncHTTPClient. there are so many things to consider when using NIO, e.g. proxy.

**Comment by anthonycastelli** [comment]
@vkill I forgot to tag this the other day, it's now available in `1.0.0-alpha.8`

**Pull request merged**
